### ISSUE TITLE
Does this have CalDAV support?

### ISSUE THREAD

**Issue by luofan189** [cozy/jsDAV#13]
Does this have CalDAV support? It seems no implementation in the lib/CalDAV folder...

**Comment by clochix** [comment]
Hi @luofan189,
Yes, we use this library to sync calendars with CalDAV.
What do you mean by “It seems no implementation in the lib/CalDAV folder”? In this folder: https://github.com/cozy/jsDAV/tree/npm-publish-fork/lib/CalDAV ?

**Comment by luofan189** [comment]
@clochix , I meant it seems no implementation for iBackend as I only see interfaces folder, but this one has a redis backend implementation: https://github.com/mikedeboer/jsDAV/tree/master/lib/CalDAV/backends I checked cozy-sync, I think the implementation of the backend is in that repo, am I right?

**Comment by clochix** [comment]
Yes you're right, as we use CozyDB as backend.
Here's our backend: https://github.com/cozy/cozy-sync/blob/master/server/backends/caldav.coffee

**Comment by luofan189** [comment]
Thanks!
