### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by clochix** [cozy/jsDAV#17]
A user report that calendar sync is broken for a few days between Cozy and its iOS device. Here are the logs:

```
Exception:  { [Error: Calendar with name '06AA96C4-38A2-4281-B369-934F9AEA3706' could not be found] code: 404, type: 'FileNotFound', message: 'Calendar with name 
              \'06AA96C4-38A2-4281-B369-934F9AEA3706\' could not be found' }
/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/CalDAV/plugin.js:180 return callback(false); ^ TypeError: callback is not a function
at Object.module.exports.jsDAV_Plugin.extend.unknownMethod (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/CalDAV/plugin.js:180:16)
at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/shared/asyncEvents.js:57:22
at handler (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:148:21)
at Object.next (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:449:13)
at next (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:144:20)
at __dirname.end (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:368:16) 
at eventName.dispatchEvent (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/shared/asyncEvents.js:67:12)
at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAV/handler.js:253:22
at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/shared/asyncEvents.js:75:13
at handler (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:371:33)
```

What's strange is that `unknownMethod` is called whereas the method is `PUT`. Event creation from the remote client make the Sync application crash.

**Comment by 19emtuck** [comment]
thx for this issue.

**Comment by clochix** [comment]
Ok, the handling of unknown method was wrong, this patch should fix it, so the application won't crash when client send an unknown request

@19emtuck could you try to see which method your CalDAV client tries to use? 

```
grep sync /usr/local/var/log/cozy/proxy.log | grep -C 5 PUT
```

**Comment by 19emtuck** [comment]
your grep option (-C 5) gives me lots of lines. I filter too keep PUT and bellow add a complete
group, if that make sens to you.

[Fri, 01 Apr 2016 20:54:44 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 500 - 42.527 ms -  2357
[Fri, 01 Apr 2016 20:54:44 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 500 - 48.087 ms -  2357
[Fri, 01 Apr 2016 21:09:40 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 500 - 37.707 ms -  2357
[Fri, 01 Apr 2016 21:09:40 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 500 - 41.480 ms -  2357
[Fri, 01 Apr 2016 21:28:12 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 500 - 38.054 ms -  2357
[Fri, 01 Apr 2016 21:28:12 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 500 - 46.181 ms -  2357
[Fri, 01 Apr 2016 21:47:48 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 401 - 65.036 ms -  -
[Fri, 01 Apr 2016 21:47:49 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 201 - 825.654 ms -  0
[Fri, 01 Apr 2016 21:47:51 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 412 - 1575.255 ms -  -
[Sat, 02 Apr 2016 07:24:26 GMT] - PUT /public/sync/calendars/me/tuck3/418E29F4-D022-4B47-8B0A-3708277D66B3.ics - 500 - 80.341 ms -  2357
[Sat, 02 Apr 2016 07:24:27 GMT] - PUT /public/sync/calendars/me/tuck2/2A59455B-0E68-4782-9A3E-F40BF75AE05A.ics - 500 - 42.789 ms -  2357

---

[Fri, 01 Apr 2016 21:28:10 GMT] - PROPPATCH /public/sync/calendars/me/tuck3/ - 207 - 136.809 ms -  -
[Fri, 01 Apr 2016 21:28:10 GMT] - PROPFIND /public/sync/principals/me/ - 207 - 180.195 ms -  -
[Fri, 01 Apr 2016 21:28:11 GMT] - MKCALENDAR /public/sync/calendars/me/DF7A65AD-5647-42C2-8974-0658C54B1F98/ - 500 - 239.640 ms -  2357
[Fri, 01 Apr 2016 21:28:12 GMT] - MOVE /public/sync/calendars/me/tuck2/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 500 - 171.572 ms -  2357
[Fri, 01 Apr 2016 21:28:12 GMT] - PROPFIND /public/sync/calendars/me/tuck3/ - 500 - 60.855 ms -  2357
[Fri, 01 Apr 2016 21:28:12 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 500 - 38.054 ms -  2357
[Fri, 01 Apr 2016 21:28:12 GMT] - PUT /public/sync/calendars/me/tuck1/D8CCA07C-C76F-406A-B6BA-AA0CA22B3B76.ics - 500 - 46.181 ms -  2357
[Fri, 01 Apr 2016 21:46:34 GMT] - OPTIONS /public/sync/principals/me/ - 403 - 221.440 ms -  -
[Fri, 01 Apr 2016 21:46:34 GMT] - PROPFIND /public/sync/principals/me/ - 401 - 355.414 ms -  -
[Fri, 01 Apr 2016 21:46:35 GMT] - PROPFIND /public/sync/principals/me/ - 207 - 550.051 ms -  -
[Fri, 01 Apr 2016 21:46:35 GMT] - OPTIONS /public/sync/principals/me/ - 200 - 50.028 ms -  0
[Fri, 01 Apr 2016 21:46:36 GMT] - PROPFIND /public/sync/calendars/me/ - 401 - 38.302 ms -  -

**Comment by 19emtuck** [comment]
jobs done ! it works :) I can create and delete new events.
THX a lot ! Last question, when will your patch be available in the main repository
so I won't crash my cozy during next update.

**Comment by 19emtuck** [comment]
don't know if it's related, but events are created twice on the phone

**Comment by clochix** [comment]
Thanks for your feedback, I now understand what happened, it's because of the MKCALENDAR method. This method is only available for CalDAV, so due to the architecture of the library, it's handled like an unknown method, and the code of the handler had a problem that made the application crash.

Regarding the availability, we need to release a new version of this library, then update the Sync application and publish a new version of it. Calling our Release Master, Mister @aenario ;-)

Regarding the events being created twice, it may be related to the fact that now, sync works. There's something strange in your logs, I don't understand why your phone calls MKCALENDAR (a method to create a new calendar), then MOVE, and at last PUT (that create the event).
Could you provide us the logs of the proxy when you create an event on your phone, I'd like to see every request your client performs.

**Comment by poupotte** [comment]
This issue should be now fixed. Thanks @clochix.
